name: Check for Update and Build Parallel

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  builds: # We always build since it's pointless to even do the effort to not do it.
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: [public, x86-64, dev, prerelease]
        include:
          - branch: public
          - branch: x86-64
          - branch: dev
          - branch: prerelease

    steps:
      - name: Checkout Full Repo
        uses: actions/checkout@v4

      - name: Get docker-slim
        shell: bash
        run: |
          SLIM_VERSION=1.40.11

          curl --location --output ds.tar.gz https://github.com/slimtoolkit/slim/releases/download/$SLIM_VERSION/dist_linux.tar.gz
          tar -xvzf ds.tar.gz
          mv dist_linux/* $GITHUB_WORKSPACE
          rm -rfv ds.tar.gz dist_linux/

      - name: Build starter image
        shell: bash
        run: |
          cd docker

          GLUATEST_REF=holylib_v2
          docker build --build-arg="GMOD_BRANCH=${{ matrix.branch }}" --build-arg="GLUATEST_REF=$GLUATEST_REF" --tag gluatest_fat:latest .

      - name: Make slim image
        shell: bash
        env:
          GMOD_BRANCH: "${{ matrix.branch }}"
        run: |
          cd docker

          $GITHUB_WORKSPACE/docker-slim build \
            --target gluatest_fat:latest \
            --http-probe-off \
            --continue-after 30 \
            --show-clogs --show-blogs \
            --include-bin "/usr/bin/date" \
            --include-bin "/usr/bin/echo" \
            --include-bin "/usr/bin/python3" \
            --include-bin "/usr/bin/git" \
            --include-bin "/usr/bin/tar" \
            --include-bin "/usr/bin/cp" \
            --include-bin "/usr/bin/gzip" \
            --include-bin "/home/steam/gmodserver/bin/libbass.so" \
            --include-bin "/home/steam/gmodserver/bin/linux64/libbass.so" \
            --tag raphaelit7/gluatest:${{ matrix.branch }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: raphaelit7
          password: ${{ secrets.DOCKER_PAT }}

      - name: Tag and push slim image
        shell: bash
        run: |
          docker push raphaelit7/gluatest:${{ matrix.branch }}